In [17]:
import numpy as np

npA = np.array([[1,2,3],[4,5,6],[7,8,9]])
npB = np.array([[4,5,1],[1,2,3],[77,56,2]])
npM = npA *4
li = npM.tolist()
print(npA)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
b = npA %2 == 0
print(b)

[[False  True False]
 [ True False  True]
 [False  True False]]


In [21]:
print(npA.mean())

5.0
