In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1


In [20]:
scalar = torch.tensor(7)
scalar.shape

torch.Size([])

In [19]:
vector = torch.tensor([7,7])
vector.shape

torch.Size([2])

In [13]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

In [21]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1180, 0.6051, 0.0066, 0.7493],
        [0.2324, 0.3865, 0.7545, 0.3555],
        [0.0937, 0.5102, 0.3440, 0.7780]])

In [25]:
# Create random tensor with similar shape to image tensor
# height, width, color channels
random_image_tensor = torch.rand(size=(224,224,3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [26]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Creating a range of tensors and tensors-like

In [35]:
one_to_ten = torch.arange(start=0,end=10,step=2)
one_to_ten

tensor([0, 2, 4, 6, 8])

In [38]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

In [41]:
torch.matmul(torch.rand(10,7),torch.rand(7,10)).shape

torch.Size([10, 10])