In [11]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1


In [12]:
scalar = torch.tensor(7)
scalar.shape

torch.Size([])

In [13]:
vector = torch.tensor([7,7])
vector.shape

torch.Size([2])

In [14]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

In [18]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9389, 0.4602, 0.6606, 0.7383],
        [0.1809, 0.1950, 0.3821, 0.4039],
        [0.6685, 0.4055, 0.9473, 0.1134]])

In [19]:
# Create random tensor with similar shape to image tensor
# height, width, color channels
random_image_tensor = torch.rand(size=(224,224,3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [20]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Creating a range of tensors and tensors-like

In [21]:
one_to_ten = torch.arange(start=0,end=10,step=2)
one_to_ten

tensor([0, 2, 4, 6, 8])

In [22]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

In [23]:
torch.matmul(torch.rand(10,7),torch.rand(7,10)).shape

torch.Size([10, 10])

In [28]:
x = torch.arange(1,8)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7]), torch.Size([7]))

### Permute Tensor

In [31]:
x_original = torch.rand(size=(224, 224, 3))
# permute the original to rearrange the Dim order
x_permuted = x_original.permute(2,0,1)  #shifts 0 to 1, 1 to 2, 2 to 3
print(f"Previous shape: {x_original.shape}")
print(f"New Shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])


In [32]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [33]:
x[0][0]

tensor([1, 2, 3])

In [34]:
x[0][2][2]

tensor(9)

In [37]:
# You can use ':' to select 'all' of a target dimension
x[0][0][:]

tensor([1, 2, 3])

## Pytorch tensors & NumPy
* Data in NumPy -> PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor -> NumPy -> torch.Tensor.nump()

In [2]:
import torch
import numpy as np

array = np.arange(1.0,8.0)   #  NumPy DEFAULT DTYPE IS float32
tensor = torch.from_numpy(array)  #TENSOR DEFAULT DTYPE IS float64 (unless otherwise marked)
print(f"Array: {array}\nTensor: {tensor}")

Array: [1. 2. 3. 4. 5. 6. 7.]
Tensor: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


## 29. Reproducibility

In [14]:
import torch
random_tensorA = torch.rand(3,4)
random_tensorA

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [22]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensorB = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensorC = torch.rand(3,4)

In [26]:
random_tensorB, random_tensorC

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

## 30. Accessing the GPU

In [28]:
#Check if GPU is available
import torch
torch.cuda.is_available()

False

In [29]:
#Get NVIDIA card type
!nvidia-smi

zsh:1: command not found: nvidia_sni


#### Make PyTorch code hardware agnostic, so test if cuda (nvidia gpu) avaialble, if so set device, else cpu

In [30]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [31]:
device

'cpu'

### Exercises

In [61]:
import numpy as np
import torch

In [68]:
torch.manual_seed(0)
smallArray = torch.rand(7,7)
smallArray

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [53]:
smallArray.shape

torch.Size([7, 7])

In [63]:
torch.manual_seed(0)
multArray = torch.rand(1,7)
multArray

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [66]:
torch.matmul(smallArray,multArray.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])