In [11]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1


In [12]:
scalar = torch.tensor(7)
scalar.shape

torch.Size([])

In [13]:
vector = torch.tensor([7,7])
vector.shape

torch.Size([2])

In [14]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

In [18]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9389, 0.4602, 0.6606, 0.7383],
        [0.1809, 0.1950, 0.3821, 0.4039],
        [0.6685, 0.4055, 0.9473, 0.1134]])

In [19]:
# Create random tensor with similar shape to image tensor
# height, width, color channels
random_image_tensor = torch.rand(size=(224,224,3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [20]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Creating a range of tensors and tensors-like

In [21]:
one_to_ten = torch.arange(start=0,end=10,step=2)
one_to_ten

tensor([0, 2, 4, 6, 8])

In [22]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

In [23]:
torch.matmul(torch.rand(10,7),torch.rand(7,10)).shape

torch.Size([10, 10])

In [28]:
x = torch.arange(1,8)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7]), torch.Size([7]))

### Permute Tensor

In [31]:
x_original = torch.rand(size=(224, 224, 3))
# permute the original to rearrange the Dim order
x_permuted = x_original.permute(2,0,1)  #shifts 0 to 1, 1 to 2, 2 to 3
print(f"Previous shape: {x_original.shape}")
print(f"New Shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])


In [32]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [33]:
x[0][0]

tensor([1, 2, 3])

In [34]:
x[0][2][2]

tensor(9)

In [37]:
# You can use ':' to select 'all' of a target dimension
x[0][0][:]

tensor([1, 2, 3])

## Pytorch tensors & NumPy
* Data in NumPy -> PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor -> NumPy -> torch.Tensor.nump()

In [40]:
import torch
import numpy as np

array = np.arange(1.0,8.0)   #this will be float32
tensor = torch.from_numpy(array)  #Note: this will make float64 unless specified otherwise
print(f"Array: {array}\nTensor: {tensor}")

Array: [1. 2. 3. 4. 5. 6. 7.]
Tensor: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


## Reproducibility